### PR TITLE
attachments support

### PR DESCRIPTION
**Pull request by onemanstartup**
With tests, and in one commit :)

### CODE REVIEW

**Comment by jorgemanrubia** [comment]
Thank you so much @onemanstartup, this was much needed

**Comment by jorgemanrubia** [comment]
@onemanstartup could you update the README with an example of how the new attachment support is used

**Comment by shawnjung** [comment]
Awesome, Thanks!

**Comment by onemanstartup** [comment]
@jorgemanrubia I could update readme, but because usage of attachments is transparent with rails and mail gem I would copy rails readme. I don't know what exactly to write.

**Pull request merged**
