### PR TITLE
Rename namespace: Mailgun -> MailgunRails

### PR DESCRIPTION
**Pull request by zzet**
fix https://github.com/jorgemanrubia/mailgun_rails/pull/60

### CODE REVIEW

**Comment by zzet** [comment]
@jorgemanrubia Some tests are fails because of problems with gem installation.

**Comment by StephaneRob** [comment]
@zzet @jorgemanrubia what is the status of this PR?

**Comment by zzet** [comment]
@StephaneRob I'll finish this PR on weekends

**Comment by StephaneRob** [comment]
Thx @zzet !

**Pull request merged**
